### ISSUE TITLE
testEchoRead的crand冗余了

### ISSUE THREAD

**Issue by spin6lock** [ejoy/goscon#21]
https://github.com/ejoy/goscon/blob/eec3795959a70e0bca2b4cdc6accd6c299cfbba3/examples/client/main.go#L39

因为接着就`io.ReadFull(conn, rbuf[:sz])`，会覆盖掉的

**Comment by rangercyh** [comment]
理解错了吧，crand.Read目的是打乱接受的rbuf，防止write那边rand写进conn的数据读出来跟ch传过来的数据对byte[]初始化全0的情况读conn之后，下面bytes.Equal判断还正好相等了。比如wirte进conn的最后几个随机字节正好是0，然后read这边ch读出来buf最后几个字节是0，rbuf初始化是全0，读conn字节读少了，下面byte.Equal比较sz个字节正好后面都是0，就判断ok了：D，当然其实这样也不是就一定保险：）

**Comment by spin6lock** [comment]
@rangercyh 终于看懂了，一开始先打乱 rbuf，后面 io.ReadFull 读的时候只要没读完全，就会有打乱的字节导致 rbuf 和 buf 两者不一致
