### ISSUE TITLE
开发计划

### ISSUE THREAD

**Issue by terry8210** [ejoy/goscon#43]
功能

    流量压缩
    包转发：终结连接

可运维

    性能指标
    功能指标： 断线重连次数、重连平均时间、重连平均重传数据量等

协议网关

    解析协议，根据协议转发到不同服务

之前定义的未来计划，什么时候能够开始呢？

**Comment by xjdrew** [comment]
协议网关和包转发没有，别的都有了；开源版本未来不会再更新了；
