### ISSUE TITLE
关于cgo调用

### ISSUE THREAD

**Issue by idada** [ejoy/goscon#6]
你好，我最近也在做DH密钥交换，用的也是云风的C代码，我照搬了一个Go的版本，经过测试两者可以兼容，这样就可以避免掉cgo调用了。

cgo调用的开销还是挺大的，用在这样的小计算上面很不划算。

另外云风原先做的C版本存在生成0值私钥的可能，会进一步引起C程序崩溃或者Go死循环，需要改一下。

我移植的代码在这个仓库里：https://github.com/funny/crypto/tree/master/dh64

**Comment by cloudwu** [comment]
要注意,  光保证 random 不为 0 是不够的.

**Comment by cloudwu** [comment]
powmodp 的第一个参数如果为 0 会导致结果为 0 . 而结果又可能用于 DH 的第 2 个参数.
所以在做通讯协议的时候,应该严格检查. 或在 powmodp 的参数为 0 时 raise 出 error .

**Comment by xjdrew** [comment]
cgo确实会存在一些额外开销，不过这块效率不是那么关键；等有机会能把所有c调用去掉的时候再动手。

另外刚看代码，好像这行应该要给rand() & 0xffff加个括号：https://github.com/funny/crypto/blob/master/dh64/c/dh64.c#L62

**Comment by xjdrew** [comment]
cgo确实会存在一些额外开销，不过这块效率不是那么关键；等有机会能把所有c调用去掉的时候再动手。谢谢提供的go版本dh64!
